# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Yarn Test & Automerge
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bson: [4.x, 5.x, 6.x]
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile # will run `yarn install` command
      - run: yarn add bson@${{ matrix.bson }}
      - run: yarn sanity # will check if building works & if code is formatted well
      - run: yarn test
