# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Yarn Test & Automerge
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn install --frozen-lockfile # will run `yarn install` command
      - run: yarn sanity # will check if building works & if code is formatted well
      - run: yarn test
      # Want to run this afterwards to prevent attempting to merge if tests fail
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOTTOKEN }}
        if: ${{ github.event_name == 'pull_request' }}
